const productType = {
    ADD_TO_BASKET_PRODUCTS:"ADD_TO_BASKET_PRODUCTS",
    EDIT_BASKET_PRODUCTS:"EDIT_BASKET_PRODUCTS",
    REMOVE_FROM_BASKET_PRODUCTS:"REMOVE_FROM_BASKET_PRODUCTS",
    SET_PRODUCTS_SUCCESS:"SET_PRODUCTS_SUCCESS",
    SET_PRODUCTS_START:"SET_PRODUCTS_START",
    SET_PRODUCTS_ERROR:"SET_PRODUCTS_ERROR"
}
export default productType;