const basketType = {
    ADD_TO_BASKET_PRODUCTS:"ADD_TO_BASKET_PRODUCTS",
    EDIT_BASKET_PRODUCTS:"EDIT_BASKET_PRODUCTS",
    REMOVE_FROM_BASKET_PRODUCTS:"REMOVE_FROM_BASKET_PRODUCTS",
}
export default basketType;